# Generated by Django 4.1.1 on 2022-09-12 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('nombre', models.CharField(max_length=30, verbose_name='Name')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('tipo_documento', models.CharField(max_length=50, verbose_name='Tipo de documento')),
                ('numero_documento', models.CharField(max_length=50, verbose_name='Numero de documento')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='familiar',
            fields=[
                ('id_familiar', models.AutoField(primary_key=True, serialize=False)),
                ('parentesco', models.CharField(max_length=50, verbose_name='Parentesco')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='historial_signos',
            fields=[
                ('id_historial_signos', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_historial', models.DateTimeField(verbose_name='Fecha Historial')),
                ('observaciones', models.CharField(max_length=500, verbose_name='Observaciones')),
                ('id_familiar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='c3pAPP.familiar')),
            ],
        ),
        migrations.CreateModel(
            name='personal_salud',
            fields=[
                ('id_personal', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Rol')),
            ],
        ),
        migrations.CreateModel(
            name='signos_vitales',
            fields=[
                ('id_signos_vitales', models.AutoField(primary_key=True, serialize=False)),
                ('presion_sistolica', models.IntegerField(default=0)),
                ('presion_diastolica', models.IntegerField(default=0)),
                ('frecuencia_respiratoria', models.IntegerField(default=0)),
                ('glicemia', models.FloatField(default=0)),
                ('oximetria', models.FloatField(default=0)),
                ('temperatura', models.FloatField(default=0)),
                ('frecuencia_cardiaca', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='sugerencia',
            fields=[
                ('id_sugerencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_sugerencia', models.DateTimeField(verbose_name='Fecha de la sugerencia')),
                ('recomendacion_medica', models.CharField(max_length=1000, verbose_name='Recomendacion medica')),
                ('id_historial_signos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='c3pAPP.historial_signos')),
                ('id_personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='c3pAPP.personal_salud')),
            ],
        ),
        migrations.AddField(
            model_name='personal_salud',
            name='id_rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='c3pAPP.rol'),
        ),
        migrations.AddField(
            model_name='personal_salud',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('eps', models.CharField(max_length=50, verbose_name='eps')),
                ('rh', models.CharField(max_length=10, verbose_name='rh')),
                ('coordenadas', models.CharField(max_length=50, verbose_name='Coordenadas')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='historial_signos',
            name='id_paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='c3pAPP.paciente'),
        ),
        migrations.AddField(
            model_name='historial_signos',
            name='id_signos_vitales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='c3pAPP.signos_vitales'),
        ),
        migrations.CreateModel(
            name='asignacion_paciente',
            fields=[
                ('id_asignacion_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('id_familiar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='c3pAPP.familiar')),
                ('id_paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='c3pAPP.paciente')),
                ('id_personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='c3pAPP.personal_salud')),
            ],
        ),
    ]
