# Generated by Django 4.1.1 on 2022-09-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c3pAPP', '0002_rename_id_usuario_user_id_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacion_paciente',
            old_name='id_asignacion_paciente',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='familiar',
            old_name='id_familiar',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='historial_signos',
            old_name='id_historial_signos',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='id_paciente',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='personal_salud',
            old_name='id_personal',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='rol',
            old_name='id_rol',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='signos_vitales',
            old_name='id_signos_vitales',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='sugerencia',
            old_name='id_sugerencia',
            new_name='id',
        ),
    ]
