# Generated by Django 4.1.1 on 2022-09-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c3pAPP', '0003_rename_id_asignacion_paciente_asignacion_paciente_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(default=0, max_length=50, verbose_name='Telefono'),
            preserve_default=False,
        ),
    ]
