# Generated by Django 4.1.1 on 2022-09-17 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('c3pAPP', '0004_user_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
