from .asignacion_pacienteSerializer import asignacion_pacienteSerializer
from .familiarSerializer import familiarSerializer
from .historial_signosSerializer import historial_signosSerializer
from .pacienteSerializer import GETpacienteSerializer, POSTpacienteSerializer
from .personal_saludSerializer import personal_saludSerializer
from .rolSerializer import rolSerializer
from .signos_vitalesSerializer import signos_vitalesSerializer
from .sugerenciaSerializer import GETsugerenciaSerializer, POSTsugerenciaSerializer
from .usuarioSerializer import usuarioSerializer